site_name: Serpent Docs
nav:
  - Home: index.md
  - Getting Started:
    - Prerequisities: getting-started/prerequisities.md
    - Initializing an empty script: getting-started/init-empty-script.md
    - Script Syntax: getting-started/syntax.md
